### ISSUE TITLE
Question: encrypted password or plain

### ISSUE THREAD

**Issue by Soulplayer** [ckcr4lyf/deluge-dc-notif#1]
Hello,

I was wondering what password I need to use? The plain version of the deluge password of the encrypted version? I'm trying to use it in combination with cloudbox but I cannot seem to get it to work. 

Thank you!

**Comment by ckcr4lyf** [comment]
You have to use the plaintext password, the same one you type in the Deluge thinclient to connect to it.

**Comment by Soulplayer** [comment]
Okay thank you! I'll let you know if it is working :).

**Comment by Soulplayer** [comment]
No joy, is there a way to set a debug log or something?

**Comment by ckcr4lyf** [comment]
Hmm, in `dcpush.py` after line 78, you can manually add

```
print(myCmd)
```

And then manually run the script from command line like this:
`./dcpush.py [a torrent hash in your current deluge client]`

Few things to check for:
The port is the port for deluge daemon, not WebUI
Username and Password are for the Thinclient, not the WebUI password
Restart Deluge after adding it to the Execute plugin, after that it takes effect.
Run `chmod +x dcpush.py` to ensure it is executable

I shall try and improve it today for better error reporting as well.

**Comment by Soulplayer** [comment]
I get

```
 ./dcpush.py hash
sh: 1: deluge-console: not found
Traceback (most recent call last):
  File "./dcpush.py", line 92, in <module>
    i1 = myCmd.index("\nTracker status:")
ValueError: substring not found
```

**Comment by ckcr4lyf** [comment]
Humm, that means that you dont even have the `deluge-console` package, just the deluge client / daemon.

I shall try and install Deluge2 today and test it out myself. Hope I'm able to resolve it!

**Comment by Soulplayer** [comment]
Ignore my previous error. I was running in docker and did it the wrong way. I think it is python related. The docker container runs only python 3.6?

**Comment by Soulplayer** [comment]
Any ideas?

**Comment by ckcr4lyf** [comment]
Sorry not yet. I need to properly check the output for the commands in Deluge 2.0 and get back to you. Hopefully should be able to today.

**Comment by AdamKearn** [comment]
@ckcr4lyf   What if you use the Deluge API?  that returns a JSON object.   That data can then be manipulated and sent to the discord webhook.

I am not much of a python person myself,   Might be worth switching to NodeJS.
What are your thoughts on this?  I don't mind giving you a hand if it worth it to move to NodeJS

**Comment by ckcr4lyf** [comment]
@AdamKearn I'd planned initially to make it in nodejs, but the reasoning behind python was its a default in most seedbox setups and can me configured with minimal hassle, whereas the user woul dneed to setup node, and ideall npm install an http library, though using the inbuilt one wouldn't be too problematic in a small project.
I am however, working on a nodejs "post process" script to act on files - specifically `rclone` them to a remote, depending on rules & conditions.

@Soulplayer sorry I'd completely forgotten, I'll definitely try and find the bug today.

**Comment by ckcr4lyf** [comment]
Fixed in latest commit. 

@Soulplayer you can pull the new version. Keep in mind, you will need to set the variables again. For `DELUGE_VERSION` keep it as `2.0.3` or whatever, first character must be `2` if you are on version 2.
