### ISSUE TITLE
delugePush3.py IndexError

### ISSUE THREAD

**Issue by hinderaker** [ckcr4lyf/deluge-dc-notif#10]
Traceback (most recent call last):                                                                                                  
  File "/config/deluge-dc-notif/delugePush3.py", line 128, in <module>                                                              
    getState(torrentHash, torrentName, RATIO_CHECK_DELAY, False)                                                                    
  File "/config/deluge-dc-notif/delugePush3.py", line 71, in getState                                                               
    tracker = lines[7][9:]                                                                                                          
IndexError: list index out of range

**Comment by ckcr4lyf** [comment]
Hey @hinderaker , can you share your deluge version and python version? 

You can find them out by running:

```
$ deluge --version
$ python -V
```

**Comment by hinderaker** [comment]
Hey @ckcr4lyf :)

deluge 2.0.5                                                                                                                        
libtorrent: 2.0.6.0                                                                                                                 
Python: 3.10.4

**Comment by hinderaker** [comment]
Also tried it with newest docker image from linuxserver.io now.

deluge 2.1.1                                                                                                                        
libtorrent: 2.0.8.0                                                                                                                 
Python: 3.11.1

<Deferred at 0x7fc7f393e490 current result: None>                                                                                   
Traceback (most recent call last):                                                                                                  
  File "/config/deluge-dc-notif/delugePush3.py", line 128, in <module>                                                              
    getState(torrentHash, torrentName, RATIO_CHECK_DELAY, False)                                                                    
  File "/config/deluge-dc-notif/delugePush3.py", line 71, in getState                                                               
    tracker = lines[7][9:]                                                                                                          
              ~~~~~^^^                                                                                                              
IndexError: list index out of range

**Comment by ckcr4lyf** [comment]
Let me try it out with the Deluge 2 & Python 3 as well and get back to you. 

Are you running it as `python delugePush3.py [infohash]` for testing?

**Comment by hinderaker** [comment]
Yes, and it works fine during testing. Its when executed by deluged it fails.

**Comment by ckcr4lyf** [comment]
Gotcha. Are you using some kind of docker setup? 

Could you add a debug line in `delugePush3.py` :  On line 66 (here: https://github.com/ckcr4lyf/deluge-dc-notif/blob/c32e75b3bbcc25d23f8771246709602366dc97c5/delugePush3.py#L66) , add a line:

`print(lines)` 

Add the line at the same indentation as line 65. That should print out what you got, might help in tracing the problem

**Comment by hinderaker** [comment]
It sure did help! Got the following error:
deluge.common:129 ] Unable to use default config directory, exiting... ([Errno 13] Permission denied: \'/root.config\')", \'\']'

This is the exact same issue as #6. I did the same chmod -R 0777 /root and its now functioning properly. Sorry for wasting your time! :/

**Comment by hinderaker** [comment]
It creates /root/.config/deluge/ui.conf

```
{                                                                                                                                   
    "file": 1,                                                                                                                      
    "format": 1                                                                                                                     
}{                                                                                                                                  
    "default_ui": "gtk"                                                                                                             
}      
```

**Comment by ckcr4lyf** [comment]
> I did the same chmod -R 0777 /root and its now functioning properly. Sorry for wasting your time! :/

Not at all! Glad you got it working. And thanks for highlighting the issue, I shall highlight the permission possible fix in a docker setup section. Cheers
