### ISSUE TITLE
script error./

### ISSUE THREAD

**Issue by robahearts** [ckcr4lyf/deluge-dc-notif#2]
I'm getting the following errors with Python 2.7.17

> delomio@xxxxxxx:~/scripts$ ./dcpush.py
> Traceback (most recent call last):
>   File "./dcpush.py", line 126, in <module>
>     torrentHash = str(sys.argv[1])
> IndexError: list index out of range

**Comment by ckcr4lyf** [comment]
Can you let me know what version of Deluge you are on? 

P.S. you are not meant to manually call it, when you set it up with the deluge execute plugin, it will automatically pass the required arguments, such as the hash.

**Comment by robahearts** [comment]
Hi. I only executed it manually because it wasn't sending me the notifications. Deluge 1.2.15 on Ubuntu 18.04.4 LTS

**Comment by ckcr4lyf** [comment]
if you want to "test" it manually, run it like this:
`./dcpush.py [40 character torrent hash] [some text value]`

Example
`./dcpush.py ca4b435b35999440db6f86296331c381a0307662 example`

The torrent hash must be a valid hash in your client. Did you restart deluge after enabling the execute pluign?

**Comment by robahearts** [comment]
> 
> 
> if you want to "test" it manually, run it like this:
> `./dcpush.py [40 character torrent hash] [some text value]`
> 
> Example
> `./dcpush.py ca4b435b35999440db6f86296331c381a0307662 example`
> 
> The torrent hash must be a valid hash in your client. Did you restart deluge after enabling the execute pluign?

I did and got a new error:

 ./dcpush.py realtorrenthash test
> Traceback (most recent call last):
>   File "./dcpush.py", line 129, in <module>
>     query(torrentHash, torrentName, RATIO_CHECK_DELAY, False)
>   File "./dcpush.py", line 119, in query
>     myBot.send_msg(msg, torrentName, tracker, ratio_word)
>   File "./dcpush.py", line 56, in send_msg
>     response = urllib2.urlopen(req)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by ckcr4lyf** [comment]
@robahearts this means most likely that your Discord Webhook is invalid. Did you set it correctly? 
`WEBHOOK_URL = "https://discordapp.com/api/webhooks/somestuff/goeshere" #Replace with your Discord Webhook URL `

The `somestuff` and `goeshere` should be two different "IDs" that discord gives you

**Comment by robahearts** [comment]
My bad. That was an old webhook. Is working now. Thanks

**Comment by ckcr4lyf** [comment]
Glad it's working now. Closing this issue.
